server.port=8081

# Unique database for your enrolment service
spring.datasource.url=jdbc:h2:mem:enrolmentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Auto-table Creation
spring.jpa.hibernate.ddl-auto=update