server.port=8084
 
spring.datasource.url=jdbc:h2:mem:reportingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. H2 Console
# This lets you view the database in your browser at http://localhost:8083/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Hibernate
spring.jpa.hibernate.ddl-auto=update