# Give your microservice its unique port
server.port=8080

# Configure H2 Database Connection strings
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable the H2 Web Console so you can view tables in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show the SQL queries in your Eclipse console window for debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update